title: Vue en español
slogan: Slogan for website
description: Description for website
baseurl: ""
slack: "https://slack.vue-es.org"
url: "https://vue-es.org"
markdown: kramdown
highlighter: rouge
permalink: :title/
exclude: [
  Gemfile,
  Gemfile.lock,
  scss,
  assets/libs,
  node_modules,
  browser-sync.js,
  src,
  package.json,
  package-lock.json,
  README.md,
  webpack.config.js,
  yarn.lock
]
assets: 
  css: assets/css/
  svg: assets/svg/
  img: assets/img/
  js: assets/js/
sass:
  load_paths: 
    - node_modules
  sass_dir: assets/_scss
  style: :compressed
gems:
  - jekyll-avatar
  - jekyll-watch