title: Vue en español
slogan: Slogan for website
description: Description for website
baseurl: ""
url: "https://vue-es.org"
markdown: "kramdown"
exclude: [
  Gemfile,
  Gemfile.lock,
  scss,
  assets/libs,
  node_modules,
  browser-sync.js,
  src,
  package.json,
  package-lock.json,
  README.md,
  webpack.config.js,
  yarn.lock
]
assets: 
  css: assets/css/
  svg: assets/svg/
  img: assets/img/
  js: assets/js/
sass:
  sass_dir: assets/_scss
  style: :compressed